#!/bin/bash

pipewire &
wlsunset -S 7:00 -s 18:30 &
cliphist store &
xfsettingsd &
# /home/nisherii/.local/bin/Obsidian &
udisksctl monitor &
exec /usr/libexec/xfce-polkit &
iwgtk -i &
# flatpak run com.vixalien.sticky # turn off temporarily for now, make it put itself on upper corner by default
syncthing &
conky -c ~/.config/conky.conf
tomat daemon start
